export const CONTACT = [
    `FRIEND FROM THE OLD DAYS`,
    `FAMILY MEMBER`,
    `UNTRACEABLE NET USER`,
    `CASUAL ACQUAINTANCE`,
    `PREVIOUS PATRON`,
    `KNOWN FENCE AND FIXER`,
    `GANG-GOON`,
    `LOVER/EX-LOVER`,
    `REGULAR FROM THE PCS\' FAVORITE WATERING HOLE`,
    `STREET KID`,
    `MASKED STRANGER`,
    `BODEGA OWNER`,
    `FORMER ENEMY`,
    `MOBSTER`,
    `PORTS SMUGGLER`,
    `WASHED-UP VIP`,
    `CONCERNED CITIZEN`,
    `CULTIST`,
    `JOB BROKER`,
    `SOMEONE A PC OWES MONEY`,
];

export const PATRON = [
    `A POLITICIAN`,
    `A MEGACORP`,
    `AN AMBITIOUS STARTUP`,
    `A MONEY LAUNDERER`,
    `AN ARMS DEALER`,
    `A STRANGE CULT`,
    `A SECRET SOCIETY`,
    `A STREET GANG`,
    `THE CEO OF A MAJOR CORP`,
    `THEMSELVES`,
    `THEMSELVES`,
    `THEIR LOVER`,
    `SOMEONE A PC OWES MONEY`,
    `A NEARBY NEIGHBORHOOD COMMUNITY`,
    `A CLAN OF ROADRUNNERS`,
    `A CURRENT VIP`,
    `ANOTHER GROUP OF PUNKS`,
    `A RENOWNED HACKER`,
    `A FORMER ENEMY`,
    `AN AI OR OTHER NET ENTITY`,
];

export const REWARD = [
    `NOTHING. THEY DO IT OR ELSE…`,
    `NOTHING. <PLEASE HELP, YOU ARE THE ONLY ONES WHO CAN!>`,
    `A FUTURE FAVOR`,
    `INFO THEY MAY HAVE USE FOR`,
    `USEABLE GEAR`,
    `A VEHICLE`,
    `ILLEGAL GOODS THEY CAN USE OR SELL`,
    `A PLACE TO CRASH AND HIDE OUT`,
    `AN IN WITH HIGH-PAYING CLIENTELE`,
    `FAME AND EXPOSURE`,
    `GETTING RID OF HALF OF A SINGLE PC\'S DEBT`,
    `A PIECE OF EXPERIMENTAL CYBERTECH`,
    `d6K¤`,
    `d10K¤`,
    `3d10K¤`,
    `5d10K¤`,
    `3d10K¤`,
    `d10K¤`,
    `2d10K¤`,
    `2d10x10K¤`,
];

export const JOB = [
    `SABOTAGE`,
    `ESCORT`,
    `STEAL`,
    `DELIVER`,
    `THREATEN`,
    `KIDNAP`,
    `BLACKMAIL`,
    `OBSERVE`,
    `PROTECT`,
    `SAVE`,
    `DISTRACT`,
    `FIND`,
    `SMUGGLE`,
    `DESTROY`,
    `PUNISH`,
    `TRICK`,
    `FIGHT FOR`,
    `WIN OVER`,
    `PLANT`,
    `INFILTRATE`,
];

export const TARGET = [
    `A SHIPMENT OF ILLEGAL GOODS / A GANG-GOON`,
    `SOME BLACKMAIL MATERIAL / A POLITICIAN`,
    `A PIECE OF FINE ART / A RECENTLY RELEASED CRIMINAL`,
    `A PROTOTYPE WEAPON / A FRIEND`,
    `A UNIQUE VEHICLE / A SIBLING`,
    `A SERVER / A HACKER`,
    `AN OFFLINE DATABASE / A SECRET SOURCE`,
    `AN EXPERIMENTAL CURE / A DOCTOR, MEDICAL OR OTHERWISE`,
    `A SECRET HIDEOUT / A GROUP OF PUNKS`,
    `EVIDENCE OF SOME CRIME / A COP`,
    `A HIGHLY IMPORTANT VIDEO RECORDING / A CURRENT VIP-CELEB`,
    `A BUNCH OF EXPLOSIVES / A MILITARY OFFICER`,
    `A PIECE OF PROTOTYPE TECHNOLOGY / AN INVENTOR`,
    `RECORDS OF PERSONAL COMMUNICATIONS / A LOVER`,
    `A RELIC / A CULT LEADER`,
    `A PIECE OF JEWELRY / A NEO-ARISTOCRAT`,
    `AN IMPORTANT POWER SOURCE / AN AI OR OTHER NET ENTITY`,
    `SOMEONE\'S MIND PALACE / AN IMMORTAL`,
    `A SIGNED CONTRACT / A LAWYER`,
    `A DATA DUMP / THE JOURNALIST WHO MADE THAT BIG SCOOP LAST YEAR`,
];

export const LOCATION = [
    `<strong>Corp office</strong> or on an active <strong>crime scene investigation</strong>`,
    `<strong>Dive bar</strong> or known <strong>drug-trafficking den</strong>`,
    `<strong>Night club</strong> or a <strong>freight ship</strong> in port, with a labyrinth of hidden compartments`,
    `<strong>Luxury residence</strong> or a <strong>shelter</strong> hidden behind a nondescript door inside a subway station`,
    `<strong>Apartment building</strong> or a forgotten <strong>doomsday bunker</strong>`,
    `<strong>Medical facility</strong> or the <strong>set</strong> for the next holoflick in the <em>Blood Countess</em> franchise`,
    `<strong>Hideout</strong> or some <strong>sewer tunnels</strong> with Nano-infested algae`,
    `<strong>Warehouse</strong> or a <strong>meeting place</strong> for the disgustingly rich`,
    `<strong>Moving vehicle</strong> or an <strong>RV</strong> with several dead bodies hidden behind a fake wall`,
    `<strong>Underground parking garage</strong> or a fully automated <strong>protein cloning and packaging factory</strong>`,
    `<strong>Shopping mall</strong> or the <strong>ritual chamber</strong> of a strange serpent drug cult`,
    `<strong>Street corner</strong> or a network of <strong>utility tunnels</strong> booby-trapped by the street kids who live here`,
    `<strong>Street food stall</strong> or an underwater <strong>human cloning facility</strong>`,
    `<strong>Restaurant</strong> or an <strong>ancient subway tunnel</strong> accessible through a G0 crater`,
    `<strong>Factory</strong> or deep inside a <strong>lost virtual world</strong>`,
    `<strong>Drug den</strong> or in one of the top levels of the <strong>Narwhal arcology</strong>`,
    `<strong>Entertainment complex</strong> or a shelter for the <strong>severely Nano-infested</strong>`,
    `<strong>Maintenance hub</strong> or an archipelago <strong>spa retreat</strong> for the upper class`,
    `<strong>Laboratory</strong> or within <em>LifArt</em>, the largest living <strong>artwork/gallery/ artist collective</strong> in Cy`,
    `<strong>Construction site</strong> or beneath a <strong>replica pyramid</strong>`,
];

export const LOCATION_FEATURES = {
    distinct: [
        `Under renovation; paint buckets, scaffolding, etc. spread around.`,
        `Holoprojections of historical art pieces in most rooms.`,
        `Anti-Nano propaganda everywhere.`,
        `Every room is a separate floor. Two elevators service every second floor only.`,
        `Parts have been taken over by squatters engaged in a slow but deadly conflict with the owners.`,
        `Vertigo-inducing animated wallpapers.`,
        `Traces of a recent gunfight with bullet holes and soot from small fires still on the walls.`,
        `Way cleaner and more luxurious than expected.`,
        `Surprisingly rough and dirty.`,
        `Due to a hostage situation, SecOps have surrounded the building next door.`,
    ],
    hidden: [
        `Maze-like crawlspaces hidden in walls, floors, ceiling.`,
        `Hidden cameras in many rooms, planted there by someone else.`,
        `A secret room used as <em>a reaperdoc clinic</em>.`,
        `Paper-thin internal walls.`,
        `A small data node that leads into the low-res virtual hellscape of a dying world. A terrible monster guards a large ¤ stash.`,
        `Sentient maintenance system can be bribed to work with the party.`,
        `Hidden conspiracy board detailing plot behind the latest miserable headline.`,
        `In a gamma-ray protected vault sits an artifact of terrible and weird powers.`,
        `What look like mannequins are knock-off skulkers with sharp claws.`,
        `A cassette with a custom App. Has a tracker that will ping the App author as soon as it's used.`,
    ],
    danger: [
        `Large valuable art piece covered in Nano-spreading dust.`,
        `A glitching Ghost is stuck in a loop somewhere, attacking anyone who enters its vicinity.`,
        `Locked maintenance door leads to a temple of a small but violent cult.`,
        `Tech use has a 50% chance of triggering an electrical fire.`,
        `Three vials of Red Pain marked as Red-juice left on a table.`,
        `An out-of-place laser turret fires at everyone without the password.`,
        `A Cy-raging menace locked inside a padded room.`,
        `A canister with a nonhuman creature that warps reality around it if disturbed.`,
        `Mold in the walls releases sight-blocking spores when bullets hit them.`,
        `An EMP booby trap renders all electronics unusable for 10 minutes if triggered.`,
    ]
};

export const GEO = [
    `<strong>Central</strong>: the Arcs`,
    `<strong>Central</strong>: North`,
    `<strong>Central</strong>: South`,
    `<strong>Central</strong>: Undersjön`,
    `<strong>Slums</strong>: Bigmosse`,
    `<strong>Slums</strong>: Lilypond`,
    `<strong>Slums</strong>: Barnyard Fields`,
    `<strong>Slums</strong>: Laketon`,
    `<strong>Hills</strong>: Edges`,
    `<strong>Hills</strong>: Galgbacken`,
    `<strong>Hills</strong>: Oak Isles`,
    `<strong>Inbetweens</strong>: Burnchurch Hex`,
    `<strong>Inbetweens</strong>: Svärta`,
    `<strong>Inbetweens</strong>: Low Meadow`,
    `<strong>Industrial</strong>: Mosscroft`,
    `<strong>G0</strong>`,
    `<strong>Ports</strong>`,
    `Sewers and underground`,
    `On/in water`,
    `Outside of Cy`,
];

export const SECURITY = [
    `UNITED CITADEL SECURITY`,
    `SLUM ROUGHNECKS`,
    `WELL-TRAINED SECOP TEAM`,
    `MAINLY DRONES AND TURRETS`,
    `ENHANCED BEASTS`,
    `ROADRUNNER CLAN`,
    `STREET GANG`,
    `VIRID VIPERS`,
    `OFF-DUTY COPS`,
    `SECOPS AND NANOGOONS`,
    `CYBERSLASHERS`,
    `A GROUP OF PUNKS`,
    `CORP ASSASSIN STRIKE TEAM`,
    `WILD NANOPHREAKS`,
    `AI WITH WEAPON PLATFORMS`,
    `WAY MORE GUARDS THAN FIRST APPARENT`,
    `A DEATH CULT`,
    `DRUNKEN, LOW-RATE SECOPS`,
    `STEALTH-SUIT PSYCHOPATH`,
    `VINDICATOR CYDROID AND HANDLER`,
];

export const COMPLICATIONS = [
    `The contact or target starts acting against their own interest.`,
    `Rival punks interfere or are on the same contract.`,
    `Someone a PC owes money to shows up and interferes.`,
    `Nothing.`,
    `It\'s just a distraction for the patron to pull off something bigger.`,
    `It\'s a trap.`,
    `Another team of punks or SecOps will try to hunt them down as soon as the job\'s done.`,
    `Someone else gets there first.`,
    `The contact backpedals on the reward.`,
    `The contact got the situation all wrong.`,
    `The job has a very short deadline.`,
    `The contact or target is not who they claim to be.`,
    `The contact or target disappears.`,
    `There are a lot of bystanders in the way.`,
    `The contact or target is arrested.`,
    `The events are being recorded.`,
    `Everything turns to chaos.`,
    `A miserable headline occurs midway, changing the situation.`,
    `The target is a friend or loved one.`,
    `The group gets a counteroffer from someone else.`,
];
